### ISSUE TITLE
Deprecation warning with fresh simple_form

### ISSUE THREAD

**Issue by dexion** [joecorcoran/judge-simple_form#7]
DEPRECATION WARNING: judge method now accepts a `wrapper_options` argument. The method definition without the argument is deprecated and will be removed in the next Simple Form version. Change your code from:
    def judge
to
    def judge(wrapper_options)
See https://github.com/plataformatec/simple_form/pull/997 for more information.
 (called from render at ........../bundler/gems/simple_form-6c9e69b22f63/lib/simple_form/wrappers/leaf.rb:15)

**Comment by marcusg** [comment]
any chance for a merge?

**Comment by jamesmk** [comment]
Fixed in https://github.com/joecorcoran/judge-simple_form/pull/13
